# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opsly < Formula
  desc ""
  homepage "https://opslycloud.com/"
  version "0.0.1-alpha.26"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Opsly/homebrew-cli/releases/download/v0.0.1-alpha.26/opsly_Darwin_x86_64", using: CurlDownloadStrategy
      sha256 "492841aa7f9b078b71c6c533ea5babf8b9ce9e9efff4ba6c111deeb5ebca1783"

      def install
        bin.install "opsly_Darwin_x86_64" => "opsly"
      end
    end
    on_arm do
      url "https://github.com/Opsly/homebrew-cli/releases/download/v0.0.1-alpha.26/opsly_Darwin_arm64", using: CurlDownloadStrategy
      sha256 "5ce1e7770906bd310c05b618d979bb4289e2722124f3118236cbc62ee059eeca"

      def install
        bin.install "opsly_Darwin_arm64" => "opsly"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Opsly/homebrew-cli/releases/download/v0.0.1-alpha.26/opsly_Linux_x86_64", using: CurlDownloadStrategy
        sha256 "8009d40f900ffcf8de9d7806eac5a4b6a287b635cdd6ac59fd9120bc776cc59c"

        def install
          bin.install "opsly_Linux_x86_64" => "opsly"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Opsly/homebrew-cli/releases/download/v0.0.1-alpha.26/opsly_Linux_arm64", using: CurlDownloadStrategy
        sha256 "e319c7aba18c2eeb3ea1d15cca6f28bbedac47089cec7d68d3a3150edc1a5e36"

        def install
          bin.install "opsly_Linux_arm64" => "opsly"
        end
      end
    end
  end
end
