# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opsly < Formula
  desc ""
  homepage "https://opslycloud.com/"
  version "0.0.1-alpha.21"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Opsly/homebrew-cli/releases/download/v0.0.1-alpha.21/opsly_Darwin_x86_64", using: CurlDownloadStrategy
      sha256 "bf541b7463f03b39867b2e32b8a0286ecd20c0d6aadc1828b62149503c1cf3ca"

      def install
        bin.install "opsly_Darwin_x86_64" => "opsly"
      end
    end
    on_arm do
      url "https://github.com/Opsly/homebrew-cli/releases/download/v0.0.1-alpha.21/opsly_Darwin_arm64", using: CurlDownloadStrategy
      sha256 "bb59fdb5a560500233df420a9175d692e5b43a3919b3afe0eda98bd359ff490d"

      def install
        bin.install "opsly_Darwin_arm64" => "opsly"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Opsly/homebrew-cli/releases/download/v0.0.1-alpha.21/opsly_Linux_x86_64", using: CurlDownloadStrategy
        sha256 "12b807c02a2b264b01b0a38d40f18446d087f3c37dfec24e49087defab43ad60"

        def install
          bin.install "opsly_Linux_x86_64" => "opsly"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Opsly/homebrew-cli/releases/download/v0.0.1-alpha.21/opsly_Linux_arm64", using: CurlDownloadStrategy
        sha256 "427a40115eb04e0114108a1393f6d5f26c06606714f4416ce5a6f3475982ee93"

        def install
          bin.install "opsly_Linux_arm64" => "opsly"
        end
      end
    end
  end
end
